MaterialLoader support `Boolean` and `Integer` uniform data setting
galacean/engine pull request #1875
Opened 2023-11-13 02:16 UTC by Sway007

### Please check if the PR fulfills these requirements

- [ ] The commit message follows our [guidelines](https://github.com/galacean/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

### What is the current behavior? (You can also link to an open issue here)

### What is the new behavior (if this is a feature change)?

### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)

### Other information:

2023-11-13 06:24 UTC, GuoLei1990 approved these changes

2023-11-13 06:43 UTC, zhuxudong requested changes

2023-11-13 06:43 UTC, zhuxudong commented on packages/loader/src/MaterialLoader.ts
> +                materialShaderData.setInt(key, value ? 1 : 0);
break;

2023-11-14 10:21 UTC, GuoLei1990 requested changes

2023-11-14 10:21 UTC, GuoLei1990 commented on packages/shader-lab/package.json
> -  "browser": "dist/browser.js",
Delete again?

2023-11-15 06:28 UTC, Sway007 commented on packages/loader/src/MaterialLoader.ts
> +                materialShaderData.setInt(key, value ? 1 : 0);
done

2023-11-15 06:40 UTC, merged