Ignore convert to 300 if original shader is glsl300
galacean/engine pull request #2048
Opened 2024-03-25 02:23 UTC by zhuxudong

### Please check if the PR fulfills these requirements
Fix #2047 
- [x] The commit message follows our [guidelines](https://github.com/galacean/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

### What is the current behavior? (You can also link to an open issue here)

### What is the new behavior (if this is a feature change)?

### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)

### Other information:

2024-03-25 05:53 UTC, eyworldwide approved these changes

2024-04-01 09:49 UTC, GuoLei1990 requested changes
Add unit test

2024-04-01 09:49 UTC, GuoLei1990 commented on packages/core/src/shader/ShaderPass.ts
> +    if (isWebGL2 && !ShaderFactory._isGLSL300(fragmentSource)) {
Atomization is better，like three.js

2024-04-01 10:00 UTC, GuoLei1990 commented
Completed supplementary inspection：
![image](https://github.com/galacean/engine/assets/4967545/6f2312ad-8acc-4eab-9f3d-8866bc9caedb)

2024-04-02 02:59 UTC, GuoLei1990 commented
![image](https://github.com/galacean/engine/assets/4967545/21d402b1-67fa-4770-9c64-f368063d263a)
Babylon.js don't have this bug

2024-04-02 03:16 UTC, GuoLei1990 commented on packages/core/src/shaderlib/ShaderFactory.ts
> +      shader = shader.replace(/\btexture2DProj\b/g, "textureProj");
Put this line firast

2024-04-02 03:26 UTC, GuoLei1990 commented on packages/core/src/shaderlib/ShaderFactory.ts
>      shader = shader.replace(/\battribute\b/g, "in");
Only vertex need

2024-04-02 05:12 UTC, GuoLei1990 commented on packages/core/src/shaderlib/ShaderFactory.ts
> +    shader = shader.replace(/\btexture2DProj\b/g, "textureProj");
Test

2024-04-02 06:05 UTC, GuoLei1990 commented on packages/core/src/shaderlib/ShaderFactory.ts
> +    "GL_EXT_frag_depth"
WebGL don't need this

2024-04-02 06:17 UTC, GuoLei1990 commented on packages/core/src/shaderlib/ShaderFactory.ts
> +  static _hasOutput(fragmentShader: string) {
- private
- `_hasES3Output`

2024-04-02 06:19 UTC, GuoLei1990 commented on packages/core/src/shaderlib/ShaderFactory.ts
> +
Opt comments

2024-04-02 06:49 UTC, GuoLei1990 approved these changes

2024-04-02 07:46 UTC, GuoLei1990 approved these changes

2024-04-02 07:56 UTC, merged